export type Product = {
  id: string;
  brand: string;
  name: string;
  price: string;
  priceCents: number;
  premium: string;
  meta: string[];
  emoji: string;
  category: "clothing" | "accessories" | "home";
  description: string;
  sizes: string[];
  colors: string[];
  printAreas: string[];
};

const clothing: Product[] = [
  { id: "gildan-heavy-cotton-tee", brand: "Gildan", name: "Unisex Heavy Cotton Tee", price: "$8.80", priceCents: 880, premium: "$7.04", meta: ["8 sizes", "70 colors", "22 providers"], emoji: "👕", category: "clothing", description: "A classic heavyweight cotton tee. Durable, comfortable, and perfect for bold designs. Pre-shrunk jersey knit with seamless collar.", sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL"], colors: ["White", "Black", "Navy", "Red", "Royal Blue", "Sport Grey", "Dark Heather", "Forest Green"], printAreas: ["front", "back"] },
  { id: "bella-canvas-jersey-tee", brand: "Bella+Canvas", name: "Unisex Jersey Short Sleeve Tee", price: "$10.98", priceCents: 1098, premium: "$8.78", meta: ["9 sizes", "126 colors", "21 providers"], emoji: "👕", category: "clothing", description: "Ultra-soft, retail-fit jersey tee. Side-seamed for a modern silhouette. The go-to blank for premium print-on-demand.", sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"], colors: ["White", "Black", "Heather Gray", "Navy", "Red", "Athletic Heather", "Soft Cream", "True Royal"], printAreas: ["front", "back"] },
  { id: "gildan-softstyle-tshirt", brand: "Gildan", name: "Unisex Softstyle T-Shirt", price: "$7.95", priceCents: 795, premium: "$6.36", meta: ["9 sizes", "66 colors", "20 providers"], emoji: "👕", category: "clothing", description: "Lightweight softstyle fabric with a vintage feel. Great drape and fit at an unbeatable price point.", sizes: ["XS", "S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"], colors: ["White", "Black", "Sport Grey", "Navy", "Red", "Royal", "Charcoal", "Dark Heather"], printAreas: ["front", "back"] },
  { id: "comfort-colors-garment-dyed", brand: "Comfort Colors", name: "Unisex Garment-Dyed T-Shirt", price: "$12.41", priceCents: 1241, premium: "$9.93", meta: ["7 sizes", "61 colors", "12 providers"], emoji: "👕", category: "clothing", description: "Garment-dyed for a lived-in, vintage look from day one. Heavyweight ringspun cotton with a relaxed fit.", sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"], colors: ["White", "Black", "Butter", "Blue Jean", "Pepper", "Seafoam", "Ivory", "Crimson"], printAreas: ["front", "back"] },
  { id: "gildan-heavy-blend-hoodie", brand: "Gildan", name: "Heavy Blend Hoodie", price: "$21.14", priceCents: 2114, premium: "$16.91", meta: ["8 sizes", "42 colors", "18 providers"], emoji: "🧣", category: "clothing", description: "Cozy heavyweight fleece hoodie with a double-lined hood and kangaroo pocket. A best-seller for fall and winter collections.", sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"], colors: ["White", "Black", "Navy", "Sport Grey", "Red", "Royal", "Dark Heather", "Forest Green"], printAreas: ["front", "back"] },
  { id: "awdis-full-zip-hoodie", brand: "AWDIS", name: "Full Zip Hoodie", price: "$30.98", priceCents: 3098, premium: "$24.78", meta: ["5 sizes", "10 colors", "2 providers"], emoji: "🧣", category: "clothing", description: "Premium full-zip hoodie with brushed fleece lining. Modern athletic fit with metal zipper and split kangaroo pockets.", sizes: ["S", "M", "L", "XL", "2XL"], colors: ["White", "Black", "Navy", "Heather Grey", "Burgundy"], printAreas: ["front", "back"] },
  { id: "gildan-crewneck-sweatshirt", brand: "Gildan", name: "Heavy Blend Crewneck Sweatshirt", price: "$15.24", priceCents: 1524, premium: "$12.19", meta: ["8 sizes", "38 colors", "19 providers"], emoji: "👖", category: "clothing", description: "Classic crewneck sweatshirt in pill-resistant fleece. Double-needle stitching for durability. Great for oversized graphic designs.", sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL", "5XL"], colors: ["White", "Black", "Navy", "Sport Grey", "Red", "Royal", "Dark Heather", "Sand"], printAreas: ["front", "back"] },
  { id: "bella-canvas-sponge-fleece-crewneck", brand: "Bella+Canvas", name: "Unisex Sponge Fleece Crewneck", price: "$22.50", priceCents: 2250, premium: "$18.00", meta: ["6 sizes", "18 colors", "8 providers"], emoji: "👖", category: "clothing", description: "Ultra-soft sponge fleece with a retail-quality fit. Side-seamed, drop shoulder for a relaxed modern look.", sizes: ["S", "M", "L", "XL", "2XL", "3XL"], colors: ["White", "Black", "Heather Gray", "Navy", "Military Green", "Mauve"], printAreas: ["front", "back"] },
  { id: "lane-seven-premium-tee", brand: "Lane Seven", name: "Unisex Premium Tee", price: "$11.50", priceCents: 1150, premium: "$9.20", meta: ["7 sizes", "34 colors", "6 providers"], emoji: "👕", category: "clothing", description: "Heavyweight premium tee with a boxy, relaxed fit. Garment-dyed in rich, saturated colors.", sizes: ["S", "M", "L", "XL", "2XL", "3XL", "4XL"], colors: ["White", "Black", "Navy", "Sage", "Cream", "Burnt Orange", "Burgundy", "Forest"], printAreas: ["front", "back"] },
  { id: "aop-tank-top", brand: "AOP", name: "All-Over Print Tank Top", price: "$18.95", priceCents: 1895, premium: "$15.16", meta: ["5 sizes", "1 color", "4 providers"], emoji: "🩱", category: "clothing", description: "Full all-over print tank top. Your design covers the entire garment — perfect for bold, edge-to-edge artwork.", sizes: ["S", "M", "L", "XL", "2XL"], colors: ["White"], printAreas: ["all-over"] },
  { id: "rabbit-skins-toddler-tee", brand: "Rabbit Skins", name: "Toddler Fine Jersey Tee", price: "$7.80", priceCents: 780, premium: "$6.24", meta: ["4 sizes", "22 colors", "8 providers"], emoji: "👶", category: "clothing", description: "Soft fine jersey tee sized for toddlers. Ribbed collar with set-in sleeves. A favorite for kids' clothing brands.", sizes: ["2T", "3T", "4T", "5/6T"], colors: ["White", "Black", "Pink", "Light Blue", "Red", "Navy", "Heather", "Lemon"], printAreas: ["front", "back"] },
  { id: "aop-leggings", brand: "AOP", name: "All-Over Print Leggings", price: "$24.80", priceCents: 2480, premium: "$19.84", meta: ["5 sizes", "1 color", "3 providers"], emoji: "🦵", category: "clothing", description: "Full all-over print leggings with a wide elastic waistband. Four-way stretch for comfort and bold design impact.", sizes: ["XS", "S", "M", "L", "XL"], colors: ["White"], printAreas: ["all-over"] },
];

const accessories: Product[] = [
  { id: "iphone-tough-case", brand: "Generic", name: "iPhone Tough Case", price: "$12.35", priceCents: 1235, premium: "$9.88", meta: ["15 models", "1 color", "5 providers"], emoji: "📱", category: "accessories", description: "Dual-layer tough case with impact-resistant polycarbonate shell. Available for the latest iPhone models.", sizes: ["iPhone 13", "iPhone 14", "iPhone 14 Pro", "iPhone 15", "iPhone 15 Pro"], colors: ["Clear"], printAreas: ["back"] },
  { id: "samsung-snap-case", brand: "Generic", name: "Samsung Snap Case", price: "$11.20", priceCents: 1120, premium: "$8.96", meta: ["12 models", "1 color", "4 providers"], emoji: "📱", category: "accessories", description: "Slim snap-on case for Samsung Galaxy devices. Lightweight with vivid edge-to-edge printing.", sizes: ["Galaxy S23", "Galaxy S23+", "Galaxy S24", "Galaxy S24+"], colors: ["Clear"], printAreas: ["back"] },
  { id: "cotton-canvas-tote", brand: "Generic", name: "Cotton Canvas Tote Bag", price: "$10.45", priceCents: 1045, premium: "$8.36", meta: ["1 size", "5 colors", "8 providers"], emoji: "🎒", category: "accessories", description: "Sturdy cotton canvas tote with reinforced handles. Generous print area on both sides.", sizes: ["One Size"], colors: ["Natural", "Black", "Navy", "Red", "Light Blue"], printAreas: ["front", "back"] },
  { id: "kiss-cut-stickers", brand: "Generic", name: "Kiss-Cut Stickers", price: "$2.16", priceCents: 216, premium: "$1.73", meta: ["6 sizes", "1 color", "6 providers"], emoji: "📌", category: "accessories", description: "Premium vinyl kiss-cut stickers. Waterproof, scratch-resistant, and easy to peel. Great add-on product.", sizes: ["2×2\"", "3×3\"", "4×4\"", "5×5\"", "5.5×5.5\"", "6×6\""], colors: ["White"], printAreas: ["front"] },
  { id: "unisex-crew-socks", brand: "Generic", name: "Unisex Crew Socks", price: "$8.90", priceCents: 890, premium: "$7.12", meta: ["3 sizes", "1 color", "4 providers"], emoji: "🧦", category: "accessories", description: "Cushioned crew socks with all-over sublimation printing. Comfortable polyester blend with reinforced toe and heel.", sizes: ["S", "M", "L"], colors: ["White"], printAreas: ["all-over"] },
  { id: "snapback-trucker-cap", brand: "Yupoong", name: "Snapback Trucker Cap", price: "$14.30", priceCents: 1430, premium: "$11.44", meta: ["1 size", "12 colors", "6 providers"], emoji: "🎩", category: "accessories", description: "Classic structured trucker cap with mesh back and adjustable snapback closure. Embroidery or print on front panel.", sizes: ["One Size"], colors: ["White/Black", "Black", "Navy", "Red", "Charcoal", "Camo"], printAreas: ["front"] },
  { id: "aop-backpack", brand: "AOP", name: "All-Over Print Backpack", price: "$38.50", priceCents: 3850, premium: "$30.80", meta: ["1 size", "1 color", "3 providers"], emoji: "💼", category: "accessories", description: "Full all-over print backpack with padded straps and laptop compartment. Statement piece for any brand.", sizes: ["One Size"], colors: ["White"], printAreas: ["all-over"] },
  { id: "embroidered-beanie", brand: "Generic", name: "Embroidered Beanie", price: "$16.75", priceCents: 1675, premium: "$13.40", meta: ["1 size", "8 colors", "5 providers"], emoji: "🧶", category: "accessories", description: "Cuffed knit beanie with custom embroidery. Soft acrylic blend with a snug, one-size-fits-most fit.", sizes: ["One Size"], colors: ["Black", "Navy", "Heather Grey", "White", "Red", "Forest Green", "Burgundy", "Camel"], printAreas: ["front"] },
  { id: "mouse-pad", brand: "Generic", name: "Mouse Pad", price: "$6.80", priceCents: 680, premium: "$5.44", meta: ["3 sizes", "1 color", "4 providers"], emoji: "🖱", category: "accessories", description: "Smooth fabric top with non-slip rubber base. Vibrant edge-to-edge printing.", sizes: ["Small", "Medium", "Large"], colors: ["White"], printAreas: ["front"] },
  { id: "fanny-pack", brand: "Generic", name: "Fanny Pack", price: "$19.50", priceCents: 1950, premium: "$15.60", meta: ["1 size", "1 color", "3 providers"], emoji: "🧳", category: "accessories", description: "All-over print fanny pack with adjustable strap and zip compartment. Trendy and functional.", sizes: ["One Size"], colors: ["White"], printAreas: ["all-over"] },
];

const home: Product[] = [
  { id: "white-ceramic-mug-11oz", brand: "ORCA Coatings", name: "White Ceramic Mug 11oz", price: "$5.20", priceCents: 520, premium: "$4.16", meta: ["1 size", "1 color", "12 providers"], emoji: "☕", category: "home", description: "Classic 11oz white ceramic mug with a glossy finish. Dishwasher and microwave safe. The #1 best-selling POD product.", sizes: ["11oz"], colors: ["White"], printAreas: ["wrap"] },
  { id: "black-mug", brand: "Generic", name: "Black Mug 11oz / 15oz", price: "$7.19", priceCents: 719, premium: "$5.75", meta: ["2 sizes", "1 color", "5 providers"], emoji: "☕", category: "home", description: "Matte black ceramic mug available in 11oz and 15oz. Designs pop against the dark background.", sizes: ["11oz", "15oz"], colors: ["Black"], printAreas: ["wrap"] },
  { id: "ceramic-coffee-cup", brand: "ORCA Coatings", name: "Ceramic Coffee Cup", price: "$5.31", priceCents: 531, premium: "$4.25", meta: ["2 sizes", "1 color", "2 providers"], emoji: "☕", category: "home", description: "Premium ceramic coffee cup with ergonomic handle. Available in two sizes with full-wrap printing.", sizes: ["11oz", "15oz"], colors: ["White"], printAreas: ["wrap"] },
  { id: "matte-poster", brand: "Generic", name: "Matte Poster", price: "$5.65", priceCents: 565, premium: "$4.52", meta: ["12 sizes", "1 color", "8 providers"], emoji: "🖼", category: "home", description: "Museum-quality matte poster on thick, durable paper. Vivid colors with a smooth, non-glare finish.", sizes: ["8×10\"", "11×14\"", "12×16\"", "12×18\"", "16×20\"", "18×24\"", "24×36\""], colors: ["White"], printAreas: ["front"] },
  { id: "canvas-print", brand: "Generic", name: "Canvas Print", price: "$14.20", priceCents: 1420, premium: "$11.36", meta: ["10 sizes", "1 color", "6 providers"], emoji: "🖼", category: "home", description: "Gallery-wrapped canvas print on premium poly-cotton blend. Arrives ready to hang with finished edges.", sizes: ["8×10\"", "11×14\"", "12×16\"", "16×20\"", "18×24\"", "24×36\""], colors: ["White"], printAreas: ["front"] },
  { id: "scented-soy-candle", brand: "Generic", name: "Scented Soy Candle", price: "$10.82", priceCents: 1082, premium: "$8.66", meta: ["3 sizes", "3 scents", "2 providers"], emoji: "🕯", category: "home", description: "Hand-poured soy wax candle in a reusable glass jar. Custom label printing with your design.", sizes: ["4oz", "9oz", "16oz"], colors: ["Clear Glass"], printAreas: ["label"] },
  { id: "sherpa-fleece-blanket", brand: "Generic", name: "Sherpa Fleece Blanket", price: "$28.50", priceCents: 2850, premium: "$22.80", meta: ["3 sizes", "1 color", "5 providers"], emoji: "🧣", category: "home", description: "Soft sherpa fleece blanket with all-over print on one side. Cozy, plush, and machine washable.", sizes: ["30×40\"", "50×60\"", "60×80\""], colors: ["White"], printAreas: ["front"] },
  { id: "throw-pillow-case", brand: "Generic", name: "Throw Pillow Case", price: "$9.40", priceCents: 940, premium: "$7.52", meta: ["4 sizes", "1 color", "4 providers"], emoji: "🛋", category: "home", description: "Double-sided throw pillow case with hidden zipper. Machine washable polyester broadcloth.", sizes: ["14×14\"", "16×16\"", "18×18\"", "20×20\""], colors: ["White"], printAreas: ["front", "back"] },
  { id: "stainless-steel-water-bottle", brand: "Generic", name: "Stainless Steel Water Bottle", price: "$15.60", priceCents: 1560, premium: "$12.48", meta: ["2 sizes", "4 colors", "3 providers"], emoji: "🍶", category: "home", description: "Double-wall vacuum insulated water bottle. Keeps drinks cold 24hrs or hot 12hrs. Custom wrap print.", sizes: ["20oz", "32oz"], colors: ["White", "Black", "Silver", "Blue"], printAreas: ["wrap"] },
  { id: "spiral-notebook", brand: "Generic", name: "Spiral Notebook", price: "$8.15", priceCents: 815, premium: "$6.52", meta: ["2 sizes", "1 color", "4 providers"], emoji: "🌱", category: "home", description: "Spiral-bound notebook with custom printed cover. 120 lined pages on quality paper.", sizes: ["5.5×8.5\"", "8.5×11\""], colors: ["White"], printAreas: ["front cover", "back cover"] },
  { id: "bath-towel", brand: "Generic", name: "Bath Towel", price: "$19.90", priceCents: 1990, premium: "$15.92", meta: ["2 sizes", "1 color", "3 providers"], emoji: "🧖", category: "home", description: "Soft microfiber bath towel with all-over sublimation print. Lightweight and quick-drying.", sizes: ["27×55\"", "30×60\""], colors: ["White"], printAreas: ["front"] },
  { id: "greeting-card", brand: "Generic", name: "Greeting Card (Folded)", price: "$3.45", priceCents: 345, premium: "$2.76", meta: ["3 sizes", "1 color", "3 providers"], emoji: "🎈", category: "home", description: "Folded greeting card on premium cardstock with matching envelope. Perfect for seasonal collections.", sizes: ["4×6\"", "5×7\"", "A7"], colors: ["White"], printAreas: ["front", "inside", "back"] },
];

export const allProducts: Product[] = [...clothing, ...accessories, ...home];

export const categories = [
  { id: "clothing", label: "Clothing", products: clothing },
  { id: "accessories", label: "Accessories", products: accessories },
  { id: "home", label: "Home & Living", products: home },
] as const;

export function getProductById(id: string): Product | undefined {
  return allProducts.find((p) => p.id === id);
}

export function getProductsByCategory(category: Product["category"]): Product[] {
  return allProducts.filter((p) => p.category === category);
}
